"""Build the static character site. Python standard library only."""
from pathlib import Path
from html import escape
import os

ROOT = Path(__file__).resolve().parents[1]
BASE = 'https://auraofintelligence.github.io/'
TIGGY_URL = os.environ.get('TIGGY_PARTNER_URL', 'https://auraofintelligence.github.io/tiggy-bestmann/')
PAGES = [
 dict(slug='index', title='Australian Sire', intro='A writer. A traveller. Not the settling-down kind. Love and desire across a universe he intends to explore.', image='festival', alt='A long-haired Australian writer listens as a woman approaches him at a colourful worldbuilding festival.', caption='The Worldbuilding Challenge Festival. GenAI story concept.', aside='Meet the character', note='An adult science-fiction romantasy universe by Luke Nathan Hayes.', description='Australian Sire’s open universe of desire, travel, group marriage and humanity across planets, with extraterrestrial and extra-dimensional possibilities.', body='''
<p class="lead">Australian Sire is not the settling-down kind of guy. He wants to travel to every country and territory, write, meet, share, learn and teach. His relationships belong within that moving life.</p>
<p>He enjoys being alive. Good conversation, a woman’s interest, a ridiculous idea worth trying, a place he has never been. He has room in his life for all of it.</p>
<p>He is Australian, a writer and a traveller. Long hair, glasses, a ready curiosity and a sense of humour sit comfortably alongside very particular desires. He enjoys a grand setting without needing to be the grandest person in it.</p>
<p>Sire is the older, more refined expression of Luke’s romantic imagination. <a href="writer.html#three-personas">Tiggy, Sire and Luke Catalyst</a> bring three different personalities to the same vast universe.</p>
<h2>A life that leaves room</h2>
<p>He writes, makes things, learns and contributes. His stories explore the lives, relationships and futures that interest him. They also let women discover what he is about, in their own time.</p>
<p>Women initiate his first personal encounters. A woman or women open the conversation, make an offer or invite him somewhere unexpected. He responds. An ordinary afternoon becomes the beginning of a very different story.</p>
<p class="pullquote">The invitation arrives while he is getting on with living.</p>
<p>He is drawn to colour, pleasure, capability and people who enjoy exploring an idea. He has bold ambitions and an appetite for intimacy, with the humility to listen when someone opens a door into a life he knows nothing about.</p>
<h2>Relationships with a larger horizon</h2>
<p>His romantic imagination reaches into <a href="group-marriages.html">Global Group Marriages</a>: lovers, spouses and families connected across countries and cultures. It is one substantial possibility in an open life of travel, desire and discovery.</p>
<h2>A civilisation opening into the universe</h2>
<p>His universe follows humanity becoming a civilisation spread across planets, pursuing energy ambitions on the Kardashev scale and meeting extraterrestrial and extra-dimensional civilisations. Human lives unfold alongside artificial intelligences, robots and people whose worlds have developed along very different paths.</p>
<p>A hidden mountain city and an ocean civilisation are early ports of call. Further out, there are orbital gatherings, journeys between planets and encounters across dimensions. A woman opens a conversation. A shared journey follows. Years later, a message reaches him from another world.</p>
<p>Love, desire and family grow through that enormous setting. So do the ordinary pleasures: a shared home, music after dinner and manuscript pages across a kitchen table, with another planet hanging beyond the window.</p>
<p>Luke approaches this universe as a preview of futures taking shape through the work of global thinkers, researchers and builders in space, AI and robotics. The present work gives the stories their starting point; contact with other civilisations carries the fiction further.</p>
<p>Joyful responsible abundance is the life he wants to explore. Time to create. The means to travel. Good food, music, affection, useful work and relationships with room to grow.</p>'''),
 dict(slug='desire', title='What draws him', intro='Particular desires. Mutual curiosity. The possibility of sharing a much larger life.', image='theatre-reception', alt='A visibly pregnant singer in a garnet dress and her friend in emerald invite Sire to join their conversation in a future theatre lounge.', caption='An invitation after the performance. GenAI story concept.', aside='Desire and personality', note='His personal tastes and the relationships he hopes to explore.', description='Sire’s personal desires, attraction and hopes for larger relationships within a continuing life of travel.', body='''
<p class="lead">Sire has particular tastes and expansive hopes for where desire might lead. His fiction explores attraction alongside travel, group marriage and the possibility of sharing life across countries.</p>
<h2>The attraction is specific</h2>
<p>Sire has a pronounced attraction to breasts, particularly very large breasts: mazophilia and a preference for macromastia. His breeding fetish brings fertility, pregnancy and the thought of conceiving a child with a woman who shares that desire into his romantic imagination.</p>
<p>His desires are selective. Many women whose companionship Tiggy would happily enjoy fall outside Sire’s particular attractions. Sire follows the fertility fantasies and deep physical preferences that hold his attention, including those well outside conventional ideas of normal.</p>
<p>He also enjoys a quick wit, warmth, confidence, intelligence and the pleasure of someone being direct about what she wants. An unexpected question draws him into a conversation. A shared interest keeps them talking. Her invitation takes him somewhere he had never thought to imagine.</p>
<h2>Where desire leads him</h2>
<p>He imagines several women he loves and desires, pregnancies, fatherhood and reunions across countries. The anticipation of seeing a lover again belongs alongside the excitement of a first invitation. <a href="group-marriages.html">Global Group Marriages</a> explores the larger relationships within that appetite.</p>
<h2>The rest of the evening matters</h2>
<p>Music, food, clothes, movement and place all change the mood. So does the difference between watching a performer across a crowded room and talking with her after the audience has gone home.</p>
<p>There is room for opulence and for ordinary comfort: an extraordinary dress, a good meal, a laugh over a badly behaved piece of technology, a quiet place to talk. He enjoys the physical world as well as the ideas running through it.</p>
<h2>A personal exploration</h2>
<p>He enjoys the uncertainty of meeting someone new. An unexpected question catches him off guard. A laugh changes the mood. He finds himself wondering what else she has in mind.</p>
<p>Consent and enjoyment are part of the relationships he wants. The women he meets have their own reasons for approaching him, and their invitations help shape what happens next.</p>'''),
 dict(slug='writing', title='Why he writes', intro='The stories let him say what he means, then leave the reader room to recognise an affinity.', image='reading-room-invitation', alt='Two adult readers, one visibly pregnant in saffron, begin a lively conversation with Sire over an illustrated book in a colourful reading room.', caption='Two readers have something to ask him. GenAI story concept.', aside='A writer within the fiction', note='The books are part of how Sire becomes known.', description='Why Australian Sire writes, and how the books become a signal to readers who share his interests.', body='''
<p class="lead">Sire is a writer inside the story. His books let women discover the life he hopes to explore: particular desires, continuing travel and the possibilities of larger relationships.</p>
<p>A reader gets to know his way of thinking through the humour, the desires and the ideas that stay with her. Perhaps she wonders what it would be like to meet the person behind the pages. The writing gives that curiosity something substantial to work with.</p>
<h2>Writing as a signal</h2>
<p>Luke’s intention for the books is personal as well as creative: to find women who naturally harmonise with what he is expressing, through shared interest in science-fiction romantasy. The work is how he makes himself discoverable.</p>
<p>That same idea belongs to Sire. He carries on writing and living. A reader wants a conversation and starts one.</p>
<h2>A travelling life, openly expressed</h2>
<p>The books make his intentions clear: Sire is not looking to settle down. He wants a life of travel, creativity, desire and relationships across countries. He hopes a reader recognises something of her own desires in that life before she approaches him.</p>
<h2>Stories that continue</h2>
<p>A first invitation changes the day. A reunion changes what he thought he knew about someone. Across the books, familiar relationships develop alongside new encounters. In a <a href="group-marriages.html">larger marriage</a>, the same arrival means something different to each person waiting for him.</p>
<h2>A world worth spending time in</h2>
<p>Sire writes about places with histories, people with desires and meetings that leave unfinished business. A performer’s life continues after the show. A hidden city has memories its visitor has yet to discover. The next chapter follows the questions that stay with him.</p>
<p>The Australian Sire Story Forge gathers settings, relationships, rituals, mysteries and connected story possibilities. It is a place to develop the fiction and follow the echoes of one encounter through another story.</p>
<p><a class="text-link" href="https://auraofintelligence.github.io/australian-sire-story-forge/">Explore the Australian Sire Story Forge ↗</a></p>
<p>The universe is in development. This site introduces its character and possibilities; the Forge opens the workshop behind them.</p>
<p>That universe reaches through humanity’s growth across planets, Kardashev ambitions and encounters with extraterrestrial and extra-dimensional civilisations. Sire writes about the lives inside that transformation: who meets, what draws them together and how a relationship continues when the next journey leaves Earth behind.</p>'''),
 dict(slug='group-marriages', title='Global Group Marriages', intro='Love, desire and shared commitments across countries. Sire’s life keeps moving.', image='arrivals-reunion', alt='Three adult women welcome the long-haired Sire and his travel bag at a future coastal arrivals terrace, with a sea-glider docked behind them.', caption='A welcome between journeys. GenAI story concept.', aside='An expansive relationship exploration', note='A travelling writer, ongoing relationships and a world of places to meet again.', description='Global Group Marriages, the United Nations of Love marriage simulacrum and GAJRA Earth within Australian Sire’s wider scope of potential.', body='''
<p class="lead">Global Group Marriages opens an expansive possibility in Sire’s life: several adults sharing love, sexuality, family and resources across countries and cultures. His travels continue within that imagined relationship.</p>
<h2>Several people, several places</h2>
<p>The wider proposal begins with three or more adults understanding their relationships as a larger marriage. Romantic, sexual, companionate, creative and parenting bonds each have their own place. In Sire’s fiction, those relationships stretch between connected homes, shared journeys and reunions.</p>
<p>He arrives with stories from the journey. Someone has news she wanted to tell him in person. Another spouse is leaving tomorrow. Their lives overlap without following one itinerary.</p>
<h2>Desire and future generations</h2>
<p>Attraction, fertility, pregnancy and making and raising children together belong within this exploration. Sire’s hopes for fatherhood meet the desires and decisions of the people involved. Affection, humour, shared work and the pleasure of being wanted give those relationships their everyday life.</p>
<h2 id="united-nations-of-love">The United Nations of Love</h2>
<p>The <a href="https://auraofintelligence.github.io/global-group-marriages/un-of-love.html">United Nations of Love</a> is a marriage simulacrum of the United Nations. Its members are self-sovereign adult spouses from many cultures, sharing an intimate life and raising children together. A marriage covenant and family assembly bring the international metaphor into the household.</p>
<p>Languages, stories, food and celebrations meet around the same table. Diplomacy is practised between lovers and spouses; collective intelligence includes sexuality, parenting, practical experience and the knowledge each person brings. Future generations are their own children, with faces and lives in the room.</p>
<h2>From the intimate to the planetary</h2>
<p><a href="worlds.html#planetary-life">GAJRA Earth</a> carries the exploration of distinct lives in relationship towards joyful responsible abundance at a planetary scale. The marriage simulacrum is one possible expression within that much larger field of potential.</p>
<h2>The journey stays open</h2>
<p>A reunion, a travelling companion or an invitation into an existing marriage each opens a different story. Sire remains a writer and traveller. These relationships develop through the people involved, while other encounters and ways of living remain in view.</p>
<p>The wider <a href="https://auraofintelligence.github.io/global-group-marriages/framework.html">framework</a> and <a href="https://auraofintelligence.github.io/global-group-marriages/constellations.html">relationship models</a> develop the proposal. The <a href="https://auraofintelligence.github.io/global-group-marriages/world-atlas.html">World Law Atlas</a> examines present-day recognition and practical questions. The <a href="https://auraofintelligence.github.io/australian-sire-story-forge/">Story Forge</a> explores the imagined lives.
</p>'''),
 dict(slug='encounters', title='How encounters begin', intro='A woman opens the conversation. An invitation gives the day a new direction.', image='threshold', alt='An adult woman envoy opens a mountain doorway and welcomes Sire in from the rain.', caption='An envoy at a hidden threshold. GenAI story concept.', aside='Women make the first move', note='Sire responds to the connection they begin.', description='Women-led first encounters, invitations and organic serendipity in Australian Sire’s story world.', body='''
<p class="lead">Sire never initiates the first personal encounter. A woman, or women, approach him. That is a defining part of how his stories begin.</p>
<p>He might be finishing a reading, exploring a city, helping with a project or simply having a meal. Someone has a reason to speak to him. She may know his writing, be curious about his work or have an offer that changes what he thought he was doing next.</p>
<p>A reader recognises something of her own desires in his writing. She has a question, or perhaps an invitation she has been thinking about since she finished the book.</p>
<h2>An offer has a person behind it</h2>
<p>A singer starts a conversation after her performance. An envoy opens a door into a hidden civilisation. A reader asks him a question about a passage that stayed with her. A group of women invite him to join something they are creating.</p>
<p>Each invitation comes from someone with a reason to make it. Sire listens, asks questions and discovers what she has in mind.</p>
<h2>Serendipity has consequences</h2>
<p>The universe unfolds through these meetings. An invitation changes an afternoon. A relationship grows beyond it. He finds himself in a new place, a shared project or a way of living he had only explored on the page.</p>
<p>After he leaves, their conversation continues. A message arrives, a return visit takes shape, or she joins him for the next journey. Neither knows everything this meeting will mean yet.</p>
<p>He is receptive and involved. Surprise, amusement, attraction, uncertainty and delight are all part of the experience. The story develops through what they choose to share and explore.</p>
<p class="pullquote">She has something in mind. He has time to listen.</p>
<p>His boldness lives in what he is willing to imagine and participate in. The pleasure is in an encounter unfolding naturally, with mutual interest and the freedom to discover where it goes.</p>'''),
 dict(slug='worlds', title='The worlds around him', intro='Humanity across planets. Kardashev ambitions. Extraterrestrial and extra-dimensional encounters.', image='ocean', alt='A woman envoy shows Sire an engineered underwater city through a copper-ribbed glass gallery.', caption='Arrival in the sub-oceanic technate. GenAI story concept.', aside='From the Story Forge', note='A vast developing universe, introduced through the people living in it.', description='Australian Sire’s massive science-fiction romantasy universe: humanity across planets, Kardashev ambitions, AI, robotics and encounters with extraterrestrial and extra-dimensional civilisations.', body='''
<p class="lead">The Forge opens hidden societies, future cities and civilisations with histories of their own. Sire arrives while those worlds are already alive with work, pleasure and people who have somewhere else to be.</p>
<h2>Lives beyond the doorway</h2>
<p>A cryptoterrestrial envoy introduces a society hidden within the familiar world. A sub-oceanic technate makes room for engineering, everyday work and relationships beneath the sea. A worldbuilding festival brings people together through the futures they want to imagine.</p>
<p>People work, argue, cook dinner and listen to music in these places. Sire’s arrival is one event in a world that already has plenty happening.</p>
<h2>Earth is the beginning</h2>
<p>The horizon is humanity becoming a civilisation spread across planets. Orbital habitats, lunar gatherings and journeys further into space belong to that unfolding life. Kardashev ambitions bring the question of energy to a much larger scale: from the resources of a planet towards those of a star.</p>
<p>Artificial intelligences and robotics are woven through the imagined world, from everyday making and care to the construction and maintenance of places far from Earth. People still have work, pleasures, relationships and their own ideas about where to go next.</p>
<h2>Meeting other civilisations</h2>
<p>The fiction reaches into encounters with extraterrestrial and extra-dimensional civilisations. Their histories, bodies, senses and ways of living give a meeting its own surprises. An envoy invites Sire to a gathering. He hears music he has no words for yet. Their conversation begins with something as personal as why she wanted to meet him.</p>
<p>The scale keeps opening: journeys between worlds, relationships across different experiences of time and shared lives shaped by unfamiliar intelligences.</p>
<h2>A future already taking shape</h2>
<p>Luke sees today’s space, AI and robotics work as early ingredients of this much larger future. <a href="https://www.nasa.gov/moontomarsarchitecture-strategyandobjectives/">NASA’s Moon to Mars strategy</a> develops a framework for sustained human exploration beyond Earth. <a href="https://deepmind.google/blog/gemini-robotics-brings-ai-into-the-physical-world/">Google DeepMind’s Gemini Robotics work</a> connects AI models with physical action. The stories imagine lives further along those paths.</p>
<p>Meeting other civilisations and crossing dimensions belong to the speculative fiction. Luke’s present realisation is a small opening into the enormous universe he is developing.</p>
<h2>Aura and experience</h2>
<p>Aura brings questions of attention, memory, learning and intelligence into the universe. Companions, wearables, geodes and distributed minds give the fiction different ways to explore what it means to share experience.</p>
<p>The seven-torus spaces and hollow geosphere offer a distinctive visual language. Their geometry shapes rooms, instruments and ways of navigating information, giving the imagined technology a physical presence.</p>
<p>Those possibilities also reach into relationships. Shared memories, learning across cultures and staying connected between journeys give Aura a personal place in the life Sire wants to explore.</p>
<h2>Music and shared futures</h2>
<p>A song carries a character’s feeling. A rhythm introduces a scene. A melody stays with him long after an encounter. The i C. infinity music universe is one of the creative threads connected to this larger world.</p>
<h2 id="planetary-life">GAJRA Earth and planetary life</h2>
<p><a href="https://auraofintelligence.github.io/global-group-marriages/gajra-earth.html">GAJRA Earth</a> brings joyful responsible abundance into the planetary imagination: distinct people, cultures, places and intelligences in relationship. Its garland image connects different lives without making them the same. This is one of the futures explored as humanity’s reach grows beyond Earth.</p>
<h2>Distance changes the intimate</h2>
<p>A message takes light-minutes to arrive. Someone has lived through an entire evening before the reply reaches her. Time, memory and unfamiliar senses give relationships their own textures across worlds.</p>
<p><a href="https://auraofintelligence.github.io/i-C-infinity-music-universe/infinity-engine.html">Visit the Infinity Engine ↗</a></p>'''),
 dict(slug='journey', title='Every country and territory', intro='Meet. Share. Learn. Teach. The next worthwhile invitation changes the route.', image='oracle', alt='Three physical journey models stand within a star-filled hollow geosphere.', caption='The hollow geosphere as a travel oracle. GenAI story concept.', aside='An open journey', note='Returns, longer stays and changes of direction belong within the journey.', description='An opportunity-led travel oracle for Australian Sire’s ambition to visit every country and territory.', body='''
<p class="lead">Sire wants to visit every country and territory, with time to meet people, share what he knows, learn something and offer his experience to those interested. The people he meets give each visit its own meaning.</p>
<p>He wants more than a tick beside a place name. A return visit may matter more than the next border. An invitation makes a longer stay worthwhile, and new work gives a journey a different purpose.</p>
<h2>His life keeps moving</h2>
<p>Sire is not travelling towards an eventual settled life. Travel is part of the life he wants. A partner joins him for one leg; a familiar face gives him a reason to return. The route follows work, relationships and invitations as they unfold.</p>
<h2>An oracle that brings things together</h2>
<p>The travel oracle considers invitations, creative opportunities, events, seasons, transport, resources and existing commitments. Time with partners, group gatherings and family occasions shapes a route alongside readings and workshops. It also makes room for energy, changing interests and the simple desire to spend more time somewhere.</p>
<p>It shows the connections between opportunities. A reading, a workshop and a music gathering might fit into one visit. Another invitation might suit a return. Sire chooses how to respond.</p>
<h2>Right place, right time</h2>
<p>In the fiction, serendipity takes extraordinary turns. Practical travel still involves the details: when something happens, what a visit requires and what he brings to it.</p>
<p><a href="https://auraofintelligence.github.io/right-place-right-time/">Explore Right Place, Right Time ↗</a><br><a href="https://auraofintelligence.github.io/Australian-visa-activity-atlas/">Visit the Australian Visa Activity Atlas ↗</a></p>'''),
 dict(slug='abundance', title='Joyful responsible abundance', intro='A good life has room for pleasure, useful work, generosity and the people who make it worth living.', image='shared-table-evening', alt='A pregnant woman in teal calls Sire over as adult friends share a laugh and prepare dinner in a colourful coastal home.', caption='Good food, shared company and a place beside her. GenAI story concept.', aside='What abundance feels like', note='Time, capability, creativity and a generous everyday life.', description='The life Australian Sire wants to explore: shared capability, creative freedom, pleasure and time.', body='''
<p class="lead">For Sire, abundance means the freedom to travel, create and participate in a larger shared life. Time to finish the conversation. The means to meet again. Skills and resources that make more possible together.</p>
<h2>The pleasure of having enough</h2>
<p>Sire’s ambitions include travel, intimacy, beautiful places and the freedom to follow a promising idea. They also include the everyday things that make those ambitions enjoyable: rest, good meals, friendship and time without constant pressure.</p>
<p>For Sire, abundance includes the freedom to keep travelling and the means to participate in relationships across distance. A welcoming table might be part of a visit, a reunion or a stretch of travelling together. Books, music, affection, learning and practical work fill the places they share while his journey continues.</p>
<h2>What people bring together</h2>
<p>One person has a place to stay, another a skill to share, another time for a project they all care about. Shared resources change the rhythm of a day: the work gets done, dinner lasts longer and there is room to enjoy the company.</p>
<h2>Capability makes room</h2>
<p>The wider Aura work explores better access to intelligence, tools, learning and local resources. In Sire’s universe, those ideas change daily life and the futures people choose together.</p>
<p>He wants to meet, share, learn and teach. Contributing is part of his pleasure in being somewhere. It might mean helping a project, sharing a skill, making a useful introduction or bringing a story to a gathering.</p>
<p>That ambition follows humanity beyond Earth. In the larger fiction, abundance also means the energy, intelligence and practical means to sustain lives across planets. Sire is interested in how it feels to live through that change, with people he loves and more universe ahead.</p>
<h2>Responsibility in ordinary choices</h2>
<p>Time, attention and care matter. So do promises, the people affected by a decision and the work needed to keep something going. His idea of abundance includes the capacity to look after what he values.</p>
<p class="pullquote">More life to enjoy. More room to share it.</p>
<p><a class="text-link" href="https://auraofintelligence.github.io/grey-area-commons/">Explore the Grey Area Commons ↗</a></p>'''),
 dict(slug='writer', title='The writer behind Sire', intro='Luke Nathan Hayes / Luke Catalyst, Tiggy Bestmann and Australian Sire: three romantic personalities.', image='writer', alt='An imagined portrait of the long-haired writer with glasses beside a harbour.', caption='The harbour writer. GenAI portrait concept based on Luke’s photographs.', aside='Luke Nathan Hayes', note='A personal origin story and three expressions within his romantasy.', description='Luke Nathan Hayes, also known as Luke Catalyst, and the origins and different desires of Tiggy Bestmann and Australian Sire.', body='''
<p class="lead">Luke Nathan Hayes, also known as Luke Catalyst, is the person behind Tiggy Bestmann and Australian Sire. His romantasy gives three parts of his personality their own lives: the playful fool, the selective Sire and Luke himself between them.</p>
<h2 id="three-personas">Three personalities, different attractions</h2>
<p>Through building an Aura of Intelligence, Luke has spent years exploring his own biases. His fiction brings that reflection into desire, companionship and the lives he wishes to explore. The three personalities give those different appetites distinct points of view.</p>
<h3>Tiggy Bestmann</h3>
<p>Tiggy is the innocent fool with love in abundance for women of many forms and personalities. His attraction follows fun, joy, energy and exploratory companionship. He enjoys discovering someone without an absolute preference for a particular female form.</p>
<p>His name began with Luke’s childhood dog, Tiggy, and his childhood street, Bestmann Road. Tiggy was also the game of tag: an invitation to run, laugh and play. The first-pet-and-first-street naming game gave that childhood history a cheeky adult identity. <a href="https://auraofintelligence.github.io/tiggy-bestmann/fool.html#the-name">Read Tiggy’s name story.</a></p>
<h3>Australian Sire</h3>
<p>Sire is the older, more refined expression, with a much more selective romantic appetite. Fertility, pregnancy, his breeding fetish, mazophilia and a preference for macromastia draw him towards particular women and shared desires. Many women Tiggy would happily enjoy being with hold little romantic interest for Sire.</p>
<p>He explores deep biases and fetishes beyond conventional ideas of normal. He writes them openly and hopes women who share those desires recognise an affinity. His life remains one of travel, relationships and discovery.</p>
<h3>Luke Nathan Hayes / Luke Catalyst</h3>
<p>Luke is the middle ground, where Tiggy’s openness and Sire’s specificity meet. Both are balanced within his own personality. He describes himself as sexually active and available, with attraction and expression shaped by the frame of reference and the adults sharing the scene.</p>
<h2>Writing as an invitation</h2>
<p>The books are personal as well as imaginative. Luke hopes women who naturally harmonise with his intentions discover him through the stories. A reader recognises something she wants to explore and begins a conversation.</p>
<p>Sire is a writer inside the fiction too. His books introduce his desires while he goes about his life. A woman’s invitation brings those written hopes into an encounter, and the story continues between them.</p>
<h2>The person behind the universe</h2>
<p>Luke’s work ranges across practical experience, AI philosophy, self-reflection, conscious cognitive architecture and creative worldbuilding. Joyful responsible abundance runs through it: pleasure, useful work, learning, relationships and a universe still opening ahead.</p>
<h2>Follow the threads</h2>
<p>The Man and Mind site gives more room to Luke’s thinking. His world of work experience adds practical history. The Story Forge opens the developing fictional universe, with a broad range of possible scenes and connected stories.</p>
<p><a href="https://auraofintelligence.github.io/luke-nathan-hayes-man-and-mind/">Luke Nathan Hayes: Man and Mind ↗</a><br><a href="https://auraofintelligence.github.io/Lukes-world-of-work-experience/">Luke’s world of work experience ↗</a><br><a href="https://auraofintelligence.github.io/australian-sire-story-forge/">Australian Sire Story Forge ↗</a></p>
<p><a href="https://auraofintelligence.github.io/tiggy-bestmann/">Meet Tiggy Bestmann ↗</a></p>'''),
 dict(slug='sitemap', title='Find your way', intro='Follow Sire through desire, writing, travel and the larger relationships he hopes to explore.', image='seven-torus', alt='Walkways connect seven richly coloured toroidal structures, with a library, studio and garden opening from the shared space.', caption='A walk through the seven-torus world. GenAI architectural interpretation.', aside='Site map', note='Ten connected chapters. Follow the previous and next links at the foot of every page.', description='Every chapter of the Australian Sire character website.', body='''<h2>The wider creative world</h2><p>The Story Forge develops the fiction. Man and Mind explores the writer. Global Group Marriages develops the relationship models explored in its own chapter.</p><p><a href="https://auraofintelligence.github.io/global-group-marriages/">Global Group Marriages ↗</a><br><a href="https://auraofintelligence.github.io/australian-sire-story-forge/">Australian Sire Story Forge ↗</a><br><a href="https://auraofintelligence.github.io/luke-nathan-hayes-man-and-mind/sitemap.html#top">Man and Mind site map ↗</a><br><a href="https://auraofintelligence.github.io/sitemap.html">Aura of Intelligence site map ↗</a></p>''')
]

def cards(pages):
    return '<div class="chapter-grid">'+''.join(f'<a class="chapter-card" href="{p["slug"]}.html"><span class="number">{PAGES.index(p)+1:02}</span><div><h3>{escape(p["title"])}</h3><p>{escape(p["intro"])}</p></div><span aria-hidden="true">↗</span></a>' for p in pages)+'</div>'

ORACLE='''<section class="oracle" aria-labelledby="oracle-heading"><div class="oracle-inner"><h2 id="oracle-heading">What changes the journey?</h2><p>Bring a few opportunities together to explore this fictional oracle.</p><div class="oracle-controls"><label><input type="checkbox" data-opportunity value="reading"> A reader’s invitation</label><label><input type="checkbox" data-opportunity value="craft"> A place to learn</label><label><input type="checkbox" data-opportunity value="music"> An arts festival</label></div><div class="oracle-result" id="oracle-result" aria-live="polite" aria-atomic="true"><h3>A little longer here.</h3><p>With no new invitation in view, Sire stays a little longer, finishes a chapter and explores where he already is. He has no reason to hurry towards the next border.</p></div><p class="oracle-note">An illustrative sketch of the idea. These are imagined opportunities, not live travel recommendations.</p><noscript><p class="no-js">Turn on JavaScript to combine the opportunities in this example.</p></noscript></div></section>'''

for idx,p in enumerate(PAGES):
    prev=PAGES[(idx-1)%len(PAGES)]; nxt=PAGES[(idx+1)%len(PAGES)]
    nav=''.join(f'<a href="{q["slug"]}.html"'+(' aria-current="page"' if q==p else '')+f'>{escape(q["title"])}</a>' for q in PAGES)
    extra=''
    if idx==0:
        extra='''<section class="feature"><img src="assets/island-conversation.webp" alt="Two women begin a cheerful conversation with Sire beside the bodyboards at an island surf pavilion." width="1536" height="1024" loading="lazy"><div class="feature-copy"><h2>The conversation starts on shore.</h2><p>He has come in from the waves. Two women stop to talk, and one has already made him laugh. There is time to find out what brought them over.</p><p class="aside-note">After the bodyboarding session. GenAI story concept.</p><a class="text-link" href="encounters.html">How encounters begin →</a></div></section><section class="chapter-list"><h2>Get to know him</h2>'''+cards(PAGES[1:5])+ '</section>'
    if p['slug']=='journey': extra=ORACLE
    page_list='<section class="chapter-list" aria-label="All chapters">'+cards(PAGES[:-1])+'</section>' if p['slug']=='sitemap' else ''
    html=f'''<!doctype html>
<html lang="en-AU"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><meta name="description" content="{escape(p['description'],quote=True)}"><meta name="theme-color" content="#661d38"><title>{escape(p['title'])}{' | Australian Sire' if idx else ' | A world of possibilities'}</title><link rel="icon" href="assets/favicon.ico"><link rel="apple-touch-icon" href="assets/icon-180.png"><link rel="stylesheet" href="assets/site.css?v=20261001-public"><script defer src="assets/site.js?v=20261001-direct-prose"></script></head>
<body class="{'home' if idx==0 else ''}" id="top"><a class="skip" href="#main">Skip to content</a><header class="site-header"><a class="brand" href="index.html">Australian Sire</a><div class="header-links"><a href="writer.html">The writer</a><a href="sitemap.html">Site map</a><details class="menu"><summary>Explore</summary><nav aria-label="Chapters">{nav}</nav></details></div></header>
<main id="main"><div class="masthead"><h1>{'Australian<br>Sire' if idx==0 else escape(p['title'])}</h1><p class="intro">{escape(p['intro'])}</p></div><figure class="hero {'portrait' if p['slug']=='writer' else ''}"><img src="assets/{p['image']}.webp" alt="{escape(p['alt'],quote=True)}" width="1536" height="1024" fetchpriority="high"><figcaption>{escape(p['caption'])}</figcaption></figure>
{page_list}<div class="prose-layout" id="profile"><aside><p class="aside-title">{escape(p['aside'])}</p><p class="aside-note">{escape(p['note'])}</p></aside><article class="article" aria-label="{escape(p['title'])}">{p['body']}</article></div>{extra}</main>
<nav class="page-turn" aria-label="Previous and next chapters"><a rel="prev" href="{prev['slug']}.html"><span>← Previous</span><strong>{escape(prev['title'])}</strong></a><a rel="next" href="{nxt['slug']}.html"><span>Next →</span><strong>{escape(nxt['title'])}</strong></a></nav><footer class="site-footer"><p>Australian Sire · A story world by Luke Nathan Hayes<br>Adult themes. Fiction and imagination.</p><nav aria-label="Footer"><a href="sitemap.html">Site map</a><a href="writer.html">The writer</a><a href="{escape(TIGGY_URL,quote=True)}">Meet Tiggy Bestmann</a><a href="https://auraofintelligence.github.io/australian-sire-story-forge/">Story Forge</a><a href="https://auraofintelligence.github.io/loose-goose-comedy-engine/">Loose Goose Comedy Engine</a><a href="https://auraofintelligence.github.io/luke-nathan-hayes-man-and-mind/">Man and Mind</a><a href="https://github.com/auraofintelligence/australiansire/blob/main/LICENCE.md">Strange But True licence</a></nav></footer><a class="to-top" href="#top" aria-label="Back to top">↑</a></body></html>'''
    (ROOT/(p['slug']+'.html')).write_text(html,encoding='utf-8')
print(f'Built {len(PAGES)} pages.')
