"""Build the static character site. Python standard library only."""
from pathlib import Path
from html import escape

ROOT = Path(__file__).resolve().parents[1]
BASE = 'https://auraofintelligence.github.io/'
PAGES = [
 dict(slug='index', title='Australian Sire', intro='A writer. A traveller. A man with particular desires and a world of possibilities.', image='festival', alt='A long-haired Australian writer listens as a woman approaches him at a colourful worldbuilding festival.', caption='The Worldbuilding Challenge Festival. GenAI story concept.', aside='Meet the character', note='An adult science-fiction romantasy universe by Luke Nathan Hayes.', description='Meet Australian Sire: writer, traveller and explorer of desire in Luke Nathan Hayes’ science-fiction romantasy universe.', body='''
<p class="lead">Australian Sire enjoys being alive. Good conversation, a woman’s interest, a ridiculous idea worth trying, a place he has never been. He has room in his life for all of it.</p>
<p>He is Australian, a writer and a traveller. Long hair, glasses, a ready curiosity and a sense of humour sit comfortably alongside very particular desires. He can enjoy a grand setting without needing to be the grandest person in it.</p>
<h2>A life that leaves room</h2>
<p>He writes, makes things, learns and contributes. His stories explore the lives, relationships and futures that interest him. They also let women discover what he is about, in their own time.</p>
<p>Women initiate his first personal encounters. A woman or women open the conversation, make an offer or invite him somewhere unexpected. He responds. An ordinary afternoon can become the beginning of a very different story.</p>
<p class="pullquote">The invitation arrives while he is getting on with living.</p>
<p>He is drawn to colour, pleasure, capability and people who enjoy exploring an idea. He has bold ambitions and an appetite for intimacy, with the humility to listen when someone opens a door into a life he knows nothing about.</p>
<h2>A much larger horizon</h2>
<p>His world can hold a hidden mountain city, an ocean civilisation, a shared home and a kitchen table covered in manuscript pages. The extraordinary grows out of the personal: someone speaks to him, he listens, and another possibility becomes visible.</p>
<p>Joyful responsible abundance is the life he wants to explore. Time to create. The means to travel. Good food, music, affection, useful work and relationships with room to grow.</p>'''),
 dict(slug='desire', title='What draws him', intro='Beauty catches his attention. Curiosity, humour and a clear invitation give him reasons to stay.', image='theatre-reception', alt='A visibly pregnant singer in a garnet dress and her friend in emerald invite Sire to join their conversation in a future theatre lounge.', caption='An invitation after the performance. GenAI story concept.', aside='Desire and personality', note='A candid character profile, with room for his particular tastes.', description='Sire’s tastes, desires and personal biases, explored through adult science-fiction romantasy.', body='''
<p class="lead">Sire has particular tastes. His fiction gives him room to be honest about them, curious about where they lead and willing to discover more.</p>
<h2>The attraction is specific</h2>
<p>His breeding fetish, mazophilia and attraction to macromastia are part of the character. In plain terms, his desires include fertility fantasies and a pronounced attraction to breasts, particularly large breasts. These interests belong in the profile because they are part of what his romantasy explores.</p>
<p>He also enjoys a quick wit, warmth, confidence, intelligence and the pleasure of someone being direct about what she wants. A woman can draw him into a conversation through an unexpected question, a shared interest or an invitation he had never thought to imagine.</p>
<h2>The rest of the evening matters</h2>
<p>Music, food, clothes, movement and place all change the mood. So does the difference between watching a performer across a crowded room and talking with her after the audience has gone home.</p>
<p>There is room for opulence and for ordinary comfort: an extraordinary dress, a good meal, a laugh over a badly behaved piece of technology, a quiet place to talk. He enjoys the physical world as well as the ideas running through it.</p>
<h2>A personal exploration</h2>
<p>This is his personality being explored through fiction. Desire, affinity, uncertainty and discovery can all move the story. His preferences give the writing a point of view; encounters give that point of view somewhere to go.</p>
<p>Consent and enjoyment are part of the relationships he wants. The women he meets have their own reasons for approaching him, and their invitations help shape what happens next.</p>'''),
 dict(slug='writing', title='Why he writes', intro='The stories let him say what he means, then leave the reader room to recognise an affinity.', image='reading-room-invitation', alt='Two adult readers, one visibly pregnant in saffron, begin a lively conversation with Sire over an illustrated book in a colourful reading room.', caption='Two readers have something to ask him. GenAI story concept.', aside='A writer within the fiction', note='The books are part of how Sire becomes known.', description='Why Australian Sire writes, and how the books become a signal to readers who share his interests.', body='''
<p class="lead">Sire is a writer inside the story. He puts his interests, intentions and imagination into books that women can discover for themselves.</p>
<p>A reader has time to get to know his way of thinking. She can enjoy the humour, recognise a desire, disagree with an idea or wonder what it would be like to meet the person behind the pages. The writing gives that curiosity something substantial to work with.</p>
<h2>Writing as a signal</h2>
<p>Luke’s intention for the books is personal as well as creative: to find women who naturally harmonise with what he is expressing, through shared interest in science-fiction romantasy. The work is how he makes himself discoverable.</p>
<p>That same idea belongs to Sire. He carries on writing and living. A reader who wants a conversation can be the one to begin it.</p>
<h2>A world worth spending time in</h2>
<p>The stories need more than a list of preferences. They need places worth visiting, people with things to say, questions that matter and moments that change a relationship. A hidden city has its own history. A performer has a life after the show. A shared future involves everyday choices as well as extraordinary possibilities.</p>
<p>The Australian Sire Story Forge gathers settings, relationships, rituals, mysteries and connected story possibilities. It is a place to develop the fiction and explore how one encounter can echo through another story.</p>
<p><a class="text-link" href="https://auraofintelligence.github.io/australian-sire-story-forge/">Explore the Australian Sire Story Forge ↗</a></p>
<p>The universe is in development. This site introduces its character and possibilities; the Forge opens the workshop behind them.</p>'''),
 dict(slug='encounters', title='How encounters begin', intro='A woman opens the conversation. An invitation gives the day a new direction.', image='threshold', alt='An adult woman envoy opens a mountain doorway and welcomes Sire in from the rain.', caption='An envoy at a hidden threshold. GenAI story concept.', aside='Women make the first move', note='Sire responds to the connection they begin.', description='Women-led first encounters, invitations and organic serendipity in Australian Sire’s story world.', body='''
<p class="lead">Sire never initiates the first personal encounter. A woman, or women, approach him. That is a defining part of how his stories begin.</p>
<p>He might be finishing a reading, exploring a city, helping with a project or simply having a meal. Someone has a reason to speak to him. She may know his writing, be curious about his work or have an offer that changes what he thought he was doing next.</p>
<h2>An offer has a person behind it</h2>
<p>A singer starts a conversation after her performance. An envoy opens a door into a hidden civilisation. A reader asks him a question about a passage that stayed with her. A group of women invite him to join something they are creating.</p>
<p>These are possibilities for scenes. Each woman brings a voice, an intention and a life of her own. Sire gets to listen, ask questions and discover what the invitation might mean for them together.</p>
<h2>Serendipity has consequences</h2>
<p>The universe unfolds through these meetings. An invitation can change an afternoon or open a much longer relationship. It can take him into a new place, a shared project or a way of living he had only explored on the page.</p>
<p>He is receptive and involved. He can be surprised, amused, attracted, uncertain or delighted. The story develops through what they choose to share and explore.</p>
<p class="pullquote">She has something in mind. He has time to listen.</p>
<p>His boldness lives in what he is willing to imagine and participate in. The pleasure is in an encounter unfolding naturally, with mutual interest and the freedom to discover where it goes.</p>'''),
 dict(slug='worlds', title='The worlds around him', intro='Hidden cities. Ocean civilisations. Intelligent companions. Places with lives already underway.', image='ocean', alt='A woman envoy shows Sire an engineered underwater city through a copper-ribbed glass gallery.', caption='Arrival in the sub-oceanic technate. GenAI story concept.', aside='From the Story Forge', note='Settings and ideas available to the fiction, with new scenes imagined for this site.', description='The settings and ideas around Australian Sire, from hidden civilisations to Aura and shared futures.', body='''
<p class="lead">The Forge gives Sire a world much larger than the next destination. Its settings can change what a meeting means and what a shared future could become.</p>
<h2>Lives beyond the doorway</h2>
<p>A cryptoterrestrial envoy can introduce a society hidden within the familiar world. A sub-oceanic technate makes room for engineering, everyday work and relationships beneath the sea. A worldbuilding festival brings people together through the futures they want to imagine.</p>
<p>Those places need inhabitants, routines, disagreements, food, music and ways of welcoming a stranger. Sire’s arrival is one event in a world that already has plenty happening.</p>
<h2>Aura and experience</h2>
<p>Aura brings questions of attention, memory, learning and intelligence into the universe. Companions, wearables, geodes and distributed minds give the fiction different ways to explore what it means to share experience.</p>
<p>The seven-torus spaces and hollow geosphere offer a distinctive visual language. Their geometry can shape rooms, instruments and ways of navigating information, giving the imagined technology a physical presence.</p>
<h2>Music and shared futures</h2>
<p>Music can carry a character’s feeling, introduce a scene or make an encounter memorable. The i C. infinity music universe is one of the creative threads connected to this larger world.</p>
<p>Global Group Marriages opens another line of exploration: shared homes, international relationships, children, care and future generations. These ideas give the stories practical and emotional questions to live with.</p>
<p><a href="https://auraofintelligence.github.io/i-C-infinity-music-universe/infinity-engine.html">Visit the Infinity Engine ↗</a><br><a href="https://auraofintelligence.github.io/global-group-marriages/">Explore Global Group Marriages ↗</a></p>'''),
 dict(slug='journey', title='Every country and territory', intro='Meet. Share. Learn. Teach. Leave enough room for the next worthwhile invitation.', image='oracle', alt='Three physical journey models stand within a star-filled hollow geosphere.', caption='The hollow geosphere as a travel oracle. GenAI story concept.', aside='An open journey', note='An ambition that can include returns, longer stays and changes of direction.', description='An opportunity-led travel oracle for Australian Sire’s ambition to visit every country and territory.', body='''
<p class="lead">Sire wants to visit every country and territory, with time to meet people, share what he knows, learn something and teach where he can be useful.</p>
<p>A place deserves more than a tick. A return visit may matter more than the next border. An invitation can make a longer stay worthwhile, and new work can give a journey a different purpose.</p>
<h2>An oracle that brings things together</h2>
<p>The travel oracle considers invitations, creative opportunities, events, seasons, transport, resources and existing commitments. It also makes room for energy, changing interests and the simple desire to spend more time somewhere.</p>
<p>It can explain why a possibility deserves attention. A reading, a workshop and a music gathering might fit into one visit. Another invitation might be better saved for a return. Sire chooses how to respond.</p>
<h2>Right place, right time</h2>
<p>In the fiction, serendipity can be extraordinary. Practical travel still involves the details that make participation possible: when something happens, what a visit requires and what he can realistically offer.</p>
<p><a href="https://auraofintelligence.github.io/right-place-right-time/">Explore Right Place, Right Time ↗</a><br><a href="https://auraofintelligence.github.io/Australian-visa-activity-atlas/">Visit the Australian Visa Activity Atlas ↗</a></p>'''),
 dict(slug='abundance', title='Joyful responsible abundance', intro='A good life has room for pleasure, useful work, generosity and the people who make it worth living.', image='shared-table-evening', alt='A pregnant woman in teal calls Sire over as adult friends share a laugh and prepare dinner in a colourful coastal home.', caption='Good food, shared company and a place beside her. GenAI story concept.', aside='What abundance feels like', note='Time, capability, creativity and a generous everyday life.', description='The life Australian Sire wants to explore: shared capability, creative freedom, pleasure and time.', body='''
<p class="lead">Abundance is having time to finish the conversation. Enough food to invite someone to stay. Useful tools, room to create and people who enjoy making a life together.</p>
<h2>The pleasure of having enough</h2>
<p>Sire’s ambitions include travel, intimacy, beautiful places and the freedom to follow a promising idea. They also include the everyday things that make those ambitions enjoyable: rest, good meals, friendship and time without constant pressure.</p>
<p>A shared home can hold books, music, affection, learning and practical work. A festival can give people somewhere to make things, meet and enjoy what others have created. Beauty and usefulness can belong in the same place.</p>
<h2>Capability makes room</h2>
<p>The wider Aura work asks what becomes possible when people have better access to intelligence, tools, learning and local resources. In Sire’s universe, those ideas can change daily life and the kinds of futures people can choose together.</p>
<p>He wants to meet, share, learn and teach. Contributing is part of his pleasure in being somewhere. It might mean helping a project, sharing a skill, making a useful introduction or bringing a story to a gathering.</p>
<h2>Responsibility in ordinary choices</h2>
<p>Time, attention and care matter. So do promises, the people affected by a decision and the work needed to keep something going. His idea of abundance includes the capacity to look after what he values.</p>
<p class="pullquote">More life to enjoy. More room to share it.</p>
<p><a class="text-link" href="https://auraofintelligence.github.io/grey-area-commons/">Explore the Grey Area Commons ↗</a></p>'''),
 dict(slug='writer', title='The writer behind Sire', intro='Luke Nathan Hayes is building a story world around desire, intelligence, travel and the possibilities of a good life.', image='writer', alt='An imagined portrait of the long-haired writer with glasses beside a harbour.', caption='The harbour writer. GenAI portrait concept based on Luke’s photographs.', aside='Luke Nathan Hayes', note='The person, the character and the work in progress.', description='Luke Nathan Hayes and the personal intentions behind Australian Sire.', body='''
<p class="lead">Australian Sire is close to Luke’s interests and intentions. Fiction gives those interests room to travel into extraordinary places and lives.</p>
<p>Luke’s work ranges across practical experience, AI philosophy, self-reflection, conscious cognitive architecture and creative worldbuilding. The question of what a joyful, responsible and abundant life could look like runs through these projects.</p>
<h2>Putting himself into the work</h2>
<p>The writing is personal. Luke wants his science-fiction romantasy to express enough of his personality and desires that women who naturally share an affinity can discover him through it.</p>
<p>Sire is a writer too. That connection lets the fiction explore what happens when a story becomes the beginning of a conversation, an invitation or a relationship.</p>
<h2>Follow the threads</h2>
<p>The Man and Mind site gives more room to Luke’s thinking. His world of work experience adds practical history. The Story Forge opens the developing fictional universe, with a broad range of possible scenes and connected stories.</p>
<p><a href="https://auraofintelligence.github.io/luke-nathan-hayes-man-and-mind/">Luke Nathan Hayes: Man and Mind ↗</a><br><a href="https://auraofintelligence.github.io/Lukes-world-of-work-experience/">Luke’s world of work experience ↗</a><br><a href="https://auraofintelligence.github.io/australian-sire-story-forge/">Australian Sire Story Forge ↗</a></p>
<p>Tiggy Bestmann has a separate exploration. This is Australian Sire’s place: a direct introduction to his personality, desires and possible worlds.</p>'''),
 dict(slug='sitemap', title='Find your way', intro='Read in order, follow an interest, or return to the part that stayed with you.', image='seven-torus', alt='Walkways connect seven richly coloured toroidal structures, with a library, studio and garden opening from the shared space.', caption='A walk through the seven-torus world. GenAI architectural interpretation.', aside='Site map', note='Nine connected chapters. Follow the previous and next links at the foot of every page.', description='Every chapter of the Australian Sire character website.', body='''<h2>The wider creative world</h2><p>The Story Forge develops the fiction. Man and Mind explores the writer. The other linked projects open particular ideas in more detail.</p><p><a href="https://auraofintelligence.github.io/australian-sire-story-forge/">Australian Sire Story Forge ↗</a><br><a href="https://auraofintelligence.github.io/luke-nathan-hayes-man-and-mind/sitemap.html#top">Man and Mind site map ↗</a><br><a href="https://auraofintelligence.github.io/sitemap.html">Aura of Intelligence site map ↗</a></p>''')
]

def cards(pages):
    return '<div class="chapter-grid">'+''.join(f'<a class="chapter-card" href="{p["slug"]}.html"><span class="number">{PAGES.index(p)+1:02}</span><div><h3>{escape(p["title"])}</h3><p>{escape(p["intro"])}</p></div><span aria-hidden="true">↗</span></a>' for p in pages)+'</div>'

ORACLE='''<section class="oracle" aria-labelledby="oracle-heading"><div class="oracle-inner"><h2 id="oracle-heading">What changes the journey?</h2><p>Try bringing a few opportunities together. This fictional example shows how the oracle could respond.</p><div class="oracle-controls"><label><input type="checkbox" data-opportunity value="reading"> A reader’s invitation</label><label><input type="checkbox" data-opportunity value="craft"> A place to learn</label><label><input type="checkbox" data-opportunity value="music"> An arts festival</label></div><div class="oracle-result" id="oracle-result" aria-live="polite" aria-atomic="true"><h3>Leave some room in the journey.</h3><p>With no new invitation in view, Sire can stay a little longer, finish a chapter and explore where he already is. The next country can wait for a worthwhile reason to move.</p></div><p class="oracle-note">An illustrative sketch of the idea. These are imagined opportunities, not live travel recommendations.</p><noscript><p class="no-js">Turn on JavaScript to combine the opportunities in this example.</p></noscript></div></section>'''

for idx,p in enumerate(PAGES):
    prev=PAGES[(idx-1)%len(PAGES)]; nxt=PAGES[(idx+1)%len(PAGES)]
    nav=''.join(f'<a href="{q["slug"]}.html"'+(' aria-current="page"' if q==p else '')+f'>{escape(q["title"])}</a>' for q in PAGES)
    extra=''
    if idx==0:
        extra='''<section class="feature"><img src="assets/island-conversation.webp" alt="Two women begin a cheerful conversation with Sire beside the bodyboards at an island surf pavilion." width="1536" height="1024" loading="lazy"><div class="feature-copy"><h2>The conversation starts on shore.</h2><p>He has come in from the waves. Two women stop to talk, and one has already made him laugh. There is time to find out what brought them over.</p><p class="aside-note">After the bodyboarding session. GenAI story concept.</p><a class="text-link" href="encounters.html">How encounters begin →</a></div></section><section class="chapter-list"><h2>Get to know him</h2>'''+cards(PAGES[1:5])+ '</section>'
    if p['slug']=='journey': extra=ORACLE
    page_list='<section class="chapter-list" aria-label="All chapters">'+cards(PAGES[:-1])+'</section>' if p['slug']=='sitemap' else ''
    html=f'''<!doctype html>
<html lang="en-AU"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><meta name="description" content="{escape(p['description'],quote=True)}"><meta name="theme-color" content="#661d38"><title>{escape(p['title'])}{' | Australian Sire' if idx else ' | A world of possibilities'}</title><link rel="icon" href="assets/favicon.ico"><link rel="apple-touch-icon" href="assets/icon-180.png"><link rel="stylesheet" href="assets/site.css?v=20260928-art3"><script defer src="assets/site.js"></script></head>
<body class="{'home' if idx==0 else ''}" id="top"><a class="skip" href="#main">Skip to content</a><header class="site-header"><a class="brand" href="index.html">Australian Sire</a><div class="header-links"><a href="writer.html">The writer</a><a href="sitemap.html">Site map</a><details class="menu"><summary>Explore</summary><nav aria-label="Chapters">{nav}</nav></details></div></header>
<main id="main"><div class="masthead"><h1>{'Australian<br>Sire' if idx==0 else escape(p['title'])}</h1><p class="intro">{escape(p['intro'])}</p></div><figure class="hero {'portrait' if p['slug']=='writer' else ''}"><img src="assets/{p['image']}.webp" alt="{escape(p['alt'],quote=True)}" width="1536" height="1024" fetchpriority="high"><figcaption>{escape(p['caption'])}</figcaption></figure>
{'<div class="chapter-strip"><span>Desire, imagination and a life well lived.</span><a href="#profile">Meet Sire ↓</a></div>' if idx==0 else ''}{page_list}<div class="prose-layout" id="profile"><aside><p class="aside-title">{escape(p['aside'])}</p><p class="aside-note">{escape(p['note'])}</p></aside><article class="article" aria-label="{escape(p['title'])}">{p['body']}</article></div>{extra}</main>
<nav class="page-turn" aria-label="Previous and next chapters"><a rel="prev" href="{prev['slug']}.html"><span>← Previous</span><strong>{escape(prev['title'])}</strong></a><a rel="next" href="{nxt['slug']}.html"><span>Next →</span><strong>{escape(nxt['title'])}</strong></a></nav><footer class="site-footer"><p>Australian Sire · A story world by Luke Nathan Hayes<br>Adult themes. Fiction and imagination.</p><nav aria-label="Footer"><a href="sitemap.html">Site map</a><a href="writer.html">The writer</a></nav></footer><a class="to-top" href="#top" aria-label="Back to top">↑</a></body></html>'''
    (ROOT/(p['slug']+'.html')).write_text(html,encoding='utf-8')
print(f'Built {len(PAGES)} pages.')
